# Generated by Django 5.2.1 on 2025-05-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=500)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=())),
            ],
        ),
    ]
