# Generated by Django 5.2.1 on 2025-05-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_note_is_marked_note_is_trash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_marked',
            new_name='marked',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='is_trash',
            new_name='trash',
        ),
    ]
